### ISSUE TITLE
Host Record generation does not work correctly

### ISSUE THREAD

**Issue by hosunghwang** [infobloxopen/infoblox-client#21] opened 2015-11-25 21:56 UTC
When we generate a host record from HostRecordIPAllocator::allocate_ip_from_range,
The following code always returns a host record although fqdn is different.

        host_record = self.manager.find_hostname(
            dns_view, fqdn, first_ip)

fqdn is a randomly generated uuid in this case, so a different host record should be generated.
It looks like search is done in OR condition where it should be AND conditions in this case.

**Comment by bondar-pavel** [comment] 2015-11-26 10:31
Root cause is that  'name' field in not in search_fields, so fqdn is not passed on search.
https://github.com/infobloxopen/infoblox-client/blob/master/infoblox_client/objects.py#L494
I'll update HostRecord model to include that field.

**Comment by bondar-pavel** [comment] 2015-11-26 10:50
This one require more complex fix.
'name' field can act as a search_field and as updatable field, which is not common across other objects.
So introducing new new field type _updateable_search_field that is used to define fields that acts as both updateable and searchable.

**Comment by hosunghwang** [comment] 2015-12-01 00:10
I tested this and still saw the same issue.
Search came back with the wrong host record because it did not use fqdn for search.

![host_record_error](https://cloud.githubusercontent.com/assets/9219851/11488604/bb5e2638-977c-11e5-90dc-188fa34a3322.png)

**Comment by hosunghwang** [comment] 2015-12-01 00:51
The issue is that for search you are passing 'only' flag so that it does not read your new _updateable_search_field at all.

search_dict = ib_obj_for_search.to_dict(search_fields='only')

Your search_dict came back with this when I traced it.
{'ipv4addr': u'8.8.1.2', 'view': 'default'}
So sitll 'name' field is missing.

**Comment by bondar-pavel** [comment] 2015-12-01 07:21
Hosung, reason why it doesn't work for you is that fix is committed, but not yeat releases.
Need to bump version for it.
And with fix d001b49a510efc09969607e876ea0f4634dfea1f adds 'name' to searchfields too, so should work fine

**Comment by hosunghwang** [comment] 2015-12-01 07:47
Oh...I see.
Why don't you bump the version for it?

**Comment by bondar-pavel** [comment] 2015-12-01 08:16
I'll bump it today and release a new version (probably in a few hours)

**Comment by bondar-pavel** [comment] 2015-12-01 08:58
released 0.1.0 https://pypi.python.org/pypi/infoblox-client

**Closed by bondar-pavel** 2015-12-01 08:58 UTC
