### ISSUE TITLE
Comments on records?

### ISSUE THREAD

**Issue by lingfish** [infobloxopen/infoblox-client#155] opened 2017-04-12 10:33 UTC
Forgive the simple question, but I cannot work out how to set comments on a HostRecord.

Nor can I see them when searching.

eg:

`host = objects.HostRecord.create(conn, name='testings.some.domain', view='Internal', ip=my_ip, comment='Created by ZZZ')`

Doesn't set the comment in the web interface, and similarly when using `.search`, even with `return_fields`, yields nothing.

**Comment by yuewko** [comment] 2017-04-12 12:55
In order to use the "comment" field, it need to be added to the `_fields` class attribute. For example, in your case:

```
diff --git a/infoblox_client/objects.py b/infoblox_client/objects.py
index 600a11f..3749f53 100644
--- a/infoblox_client/objects.py
+++ b/infoblox_client/objects.py
@@ -539,7 +539,8 @@ class HostRecord(InfobloxObject):
 class HostRecordV4(HostRecord):
     """HostRecord for IPv4"""
     _fields = ['ipv4addrs', 'view', 'extattrs', 'name', 'zone',
-               'configure_for_dns', 'network_view', 'mac', 'ttl']
+               'configure_for_dns', 'network_view', 'mac', 'ttl',
+               'comment']
     _search_for_update_fields = ['view', 'ipv4addr', 'name',
                                  'zone', 'network_view', 'mac']
     _all_searchable_fields = _search_for_update_fields
```
Please give that a try.

Thanks!

**Comment by lingfish** [comment] 2017-04-13 02:45
Works great, thanks.  Will you update the repo?

**Comment by yuewko** [comment] 2017-04-13 04:02
Glad to hear it worked!

Fancy submitting a Pull Request? ;-)

**Comment by lingfish** [comment] 2017-04-13 06:15
I would, and not trying to avoid it, but shouldn't this change be done to multiple record objects, and hence you'd be better positioned to do that, knowing your code better?

**Comment by yuewko** [comment] 2017-04-13 12:24
Understood.

Please feel free to submit a PR (linking it to this issue) with the changes you need, and we'll pick it up from there.

**Comment by lingfish** [comment] 2017-04-14 04:46
Sure, will do.

Looking at it, basically any object in IB has comments I believe.  So, wouldn't it make sense to use a class attribute, near or at `BaseObject` or `InfobloxObject`?

**Comment by yuewko** [comment] 2017-04-14 15:47
I agree with your observation. I also think your proposed change is a good idea, but is more involved than I was anticipating.

In any case, please feel free to submit changes as you see fit. We'll definitely review and consider them.

Thanks again!

**Comment by lingfish** [comment] 2017-04-16 06:32
So I thought about doing a simple list of "common" fields, and then just using extend() to override per-class, eg: https://github.com/lingfish/infoblox-client/commit/c13ac7f036d62f3f508d22bd60744456260bf150?diff=unified

But no dice.  You're doing some voodoo in BaseObject that I don't 100% get, and I'm getting this:

```
/tmp/ipython_edit_QmGqdH/ipython_edit_5Wk3of.py in <module>()
      3 my_ip = objects.IP.create(ip=next, mac='aa:bb:cc:11:22:33', configure_for_dhcp=True)
      4
----> 5 host = objects.HostRecord.create(conn, name='testings.some.domain', view='Internal', ip=my_ip, comment='Created by xxx')
      6

/srv/virtualenv/xxx/local/lib/python2.7/site-packages/infoblox_client/objects.pyc in create(cls, connector, check_if_exists, update_if_exists, **kwargs)
    297     def create(cls, connector, check_if_exists=True,
    298                update_if_exists=False, **kwargs):
--> 299         local_obj = cls(connector, **kwargs)
    300         if check_if_exists:
    301             if local_obj.fetch(only_ref=True):

/srv/virtualenv/xxx/local/lib/python2.7/site-packages/infoblox_client/objects.pyc in __init__(self, connector, **kwargs)
    226     def __init__(self, connector, **kwargs):
    227         self.connector = connector
--> 228         super(InfobloxObject, self).__init__(**kwargs)
    229
    230     def update_from_dict(self, ip_dict, only_ref=False):

/srv/virtualenv/xxx/local/lib/python2.7/site-packages/infoblox_client/objects.pyc in __init__(self, **kwargs)
     43     def __init__(self, **kwargs):
     44         mapped_args = self._remap_fields(kwargs)
---> 45         for field in self._fields + self._shadow_fields:
     46             if field in mapped_args:
     47                 setattr(self, field, mapped_args[field])

TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

**Comment by saiprasannasastry** [comment] 2019-08-14 09:29
closing this as the issue is solved

**Closed by saiprasannasastry** 2019-08-14 09:29 UTC
