### ISSUE TITLE
nios_next_ip is broken on python 3.6.8

### ISSUE THREAD

**Issue by getsomebread** [infobloxopen/infoblox-client#241] opened 2019-12-20 16:59 UTC
I've been successfully using infoblox-client with python 2.7.5 on CentOS7. However, when using the same infoblox-client 0.4.23 with python 3.6.8 on CentOS8, I get a failure when using nios_next_ip. My ansible code will work with python 3.6.8+infoblox-client with nios_host_record if I hard-code the 'ipaddress' value. However, when I use nios_next_ip with 3.6.8, I consistently get this error:

An unhandled exception occurred while running the lookup plugin 'nios_next_ip'. Error was a <class 'Exception'>, original message: infoblox-client is required but does not appear to be installed.

**Comment by JonasKs** [comment] 2019-12-20 17:08
Please post entire stack trace, not just the last part. 

I can confirm it works on 3.6, 3.7 and 3.8. There has to be something else.

**Comment by ryebread157** [comment] 2019-12-20 17:54
I used '-vvvv' to ansible-playbook and below is all I got from that, if there is another command I should use to get debug info, let me know! Thanks.

```
TASK [Find next available IP] *********************************************************************************************************
task path: /home/foo/git/ansible-playbooks/create_infoblox_host.yml:32
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'nios_next_ip'. Error was a <class 'Exception'>, original message: infoblox-client is required but does not appear to be installed.  It can be installed using the command `pip install infoblox-client`"
}
```

**Comment by JonasKs** [comment] 2019-12-20 23:12
To be honest it looks like you haven’t installed infoblox-client in your Python 3.x environment. Do a `python3.6 -m pip install Infoblox-client`.

**Comment by bmillemathias-1a** [comment] 2020-04-27 11:49
@ryebread157 could you answer to this issue ?

**Comment by sarya-infoblox** [comment] 2022-02-17 10:49
Hi @getsomebread, can you confirm if the solution provided above resolves your problem?

**Comment by sarya-infoblox** [comment] 2022-03-09 07:49
Hi @getsomebread Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment] 2022-03-16 08:12
Closing the issue as no response from the user.

**Closed by sarya-infoblox** 2022-03-16 08:12 UTC
Labels: question
