### ISSUE TITLE
Verification Issue

### ISSUE THREAD

**Issue by ku0100** [infobloxopen/infoblox-client#154] opened 2017-03-29 21:31 UTC
I am getting authorization issues when trying to login:

Traceback (most recent call last):
...
File "my\install\directory.py", line 162, in _validate_authorized
   raise ib_ex.InfobloxBadWAPICredential(response='')
infoblox_client.exceptions.InfobloxBadWAPICredential: Infoblox IPAM is misconfigured: infoblox_username and infoblox_password are incorrect.

Here is where I am stumped, first, I thought this infoblox-client repository was for the NIOS appliance (like the description states), so I'm wondering why I am even seeing an IPAM misconfiguration line.

Second, I have verified my username and password numerous times and they allow me to login to the infoblox NIOS appliance when I go to the url manually.

Thanks for your help

**Comment by yuewko** [comment] 2017-03-29 22:27
Would you  mind providing a copy of the code that is causing the exception? Please also provide any relevant screen output/log messages.

We'll look into it.

**Comment by ku0100** [comment] 2017-03-29 23:17
Right now, I'm just testing the connection. Code is as follows:

>>> from infoblox_client import connector
>>> from infoblox_client import objects
>>> opts = {'host': 'ip_of_our_NIOS', 'username': 'my_username', 'password': 'my_password'}
>>> conn = connector.Connector(opts)
>>> nw = conn.get_object('record:host', {'ipv4addr~': 'some_test_ip'})

C:\...\site-packages\requests\packages\urllib3\connectionpool.py:852: InsecureRequestWar
ning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.
readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\site-packages\infoblox_client\connector.py", line 41, in callee return func(*args, **kwargs)
  File "C:\...\site-packages\infoblox_client\connector.py", line 250, in get_object ib_object = self._get_object(obj_type, url)
  File "C:\...\site-packages\infoblox_client\connector.py", line 269, in _get_object self._validate_authorized(r)
  File "C:\...\site-packages\infoblox_client\connector.py", line 162, in _validate_authorized raise ib_ex.InfobloxBadWAPICredential(response='')
infoblox_client.exceptions.InfobloxBadWAPICredential: Infoblox IPAM is misconfigured: infoblox_username and infoblox_password are incorrect.

Please let me know if you need any other info. Thank you

**Comment by yuewko** [comment] 2017-03-30 13:48
Could you please run the following command? This is effectively what the above code does...

`curl -k1 -u my_username:my_password -X GET "https://ip_of_our_NIOS/wapi/v1.4/record:host?ipv4addr~=some_test_ip"`

**Comment by ku0100** [comment] 2017-03-30 14:03
I am getting a syntax error at the username:password part. Using python 3.6 thru powershell.

**Comment by yuewko** [comment] 2017-03-30 14:06
If your username/password has any special characters, you would have to quote it appropriately. I suspect that it's the same for the python code. You might have to quote it as a raw string.

**Comment by ku0100** [comment] 2017-03-30 14:09
Yes I tried that originally and then I just tried without the quotes, still no dice. I also tried it on my Macbook and it gave me the same error as well.

**Comment by yuewko** [comment] 2017-03-30 14:36
In the python code, have you tried this?...

`opts = {'host': 'ip_of_our_NIOS', 'username': r"my_username", 'password': r"my_password"}`

If that still doesn't work, would it be possible to setup a NIOS account with very simple username/password and try with that?

**Comment by ku0100** [comment] 2017-03-30 15:03
Ok so now I'm getting the following tracebacks which are different than the original:

Traceback (most recent call last):

  File "C:\...\site-packages\infoblox_client\connector.py", line 192, in _parse_repl
    return jsonutils.loads(request.content)
  File "C:\...\site-packages\oslo_serialization\jsonutils.py", line 241, in loads
    return json.loads(encodeutils.safe_decode(s, encoding), **kwargs)
  File "C:\...\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\...\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\...\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "C:\...\site-packages\infoblox_client\connector.py", line 41, in callee
    return func(*args, **kwargs)
  File "C:\...\site-packages\infoblox_client\connector.py", line 250, in get_object
    ib_object = self._get_object(obj_type, url)
  File "C:\...\site-packages\infoblox_client\connector.py", line 274, in _get_object
    return self._parse_reply(r)
  File "C:\...\site-packages\infoblox_client\connector.py", line 194, in _parse_repl
    raise ib_ex.InfobloxConnectionError(reason=request.content)
infoblox_client.exceptions.InfobloxConnectionError: Infoblox HTTP request failed with: b'<HTML><HEAD><META HTTP-EQUI
EFRESH" CONTENT = "0; URL=https://ip_of_our_NIOS"/></HEAD><BODY BGCOLOR="FFFFFF">Click <A HREF="https://ip_of_our_NIOS">he
A> if page does not refresh in 10 seconds.</BODY></HTML>\n'

**Comment by ku0100** [comment] 2017-03-30 15:18
Ok tried that and this is the new output!

Traceback (most recent call last):
  File "C:\...\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\...\lib\site-packages\requests\packages\urllib3\util\connection.py", line 60, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\...\lib\socket.py", line 743, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\...\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\...\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "C:\...\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in conn
ect conn = self._new_conn()
  File "C:\...\lib\site-packages\requests\packages\urllib3\connection.py", line 150, in _new
_conn self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x033F0B10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\lib\site-packages\requests\adapters.py", line 423, in send timeout=timeout
  File "C:\...\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 678, in urlopen
    **response_kw)
  File "C:\...\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 678, in urlopen
    **response_kw)
  File "C:\...\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 678, in urlopen
    **response_kw)
  File "C:\...\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\...\lib\site-packages\requests\packages\urllib3\util\retry.py", line 376, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /infoblox.net.umd.edu/ui/wapi/v1.4/record%3Ahost?ipv4addr~=some_host_ip (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x033F0B10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\...\lib\site-packages\infoblox_client\connector.py", line 41, in callee return func(*args, **kwargs)
  File "C:\...\lib\site-packages\infoblox_client\connector.py", line 250, in get_object ib_object = self._get_object(obj_type, url)
  File "C:\...\lib\site-packages\infoblox_client\connector.py", line 267, in _get_object r = self.session.get(url, **opts)
  File "C:\...\lib\site-packages\requests\sessions.py", line 501, in get return self.request('GET', url, **kwargs)
  File "C:\...\lib\site-packages\requests\sessions.py", line 488, in request resp = self.send(prep, **send_kwargs)
  File "C:\...\lib\site-packages\requests\sessions.py", line 609, in send r = adapter.send(request, **kwargs)
  File "C:\...\lib\site-packages\requests\adapters.py", line 487, in send raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /infobl
ox.net.umd.edu/ui/wapi/v1.4/record%3Ahost?ipv4addr~=some_test_ip (Caused by NewConnectionError('<requests.packages.urllib3
.connection.VerifiedHTTPSConnection object at 0x033F0B10>: Failed to establish a new connection: [Errno 11004] getaddrin
fo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\infoblox_client\connector.py", line 45, in callee raise ib_ex.InfobloxConnectionError(reason=e)
infoblox_client.exceptions.InfobloxConnectionError: Infoblox HTTP request failed with: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: /url_of_our_NIOS/ui/wapi/v1.4/record%3Ahost?ipv4addr~=some_test_ip (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x033F0B10>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

**Comment by yuewko** [comment] 2017-03-30 15:32
As I suggested earlier, would you be able to setup an account with simple username/password?

**Comment by ku0100** [comment] 2017-03-30 15:48
Unfortunately I can't create a simple account for security reasons

Do I need to be an admin to be able to communicate with infoblox through python? I have read-write access as part of my job responsibilities but I am not an administrator for our account.

**Comment by yuewko** [comment] 2017-03-30 15:54
No, you don't need to be admin to use the python client. You should be able to use the same credential to perform the same task that you can do via the GUI.

I tried using all sorts of special characters in the password, and I could not reproduce the exception that you last reported.

If possible, maybe you can changed the password to eliminate a special character one at a time?

**Comment by johnbelamaric** [comment] 2017-03-30 16:27
The original exception had a certificate validation error. If you are using a self-signed certificate then you need to allow insecure, or include the cert in the request.

---
John Belamaric
(240) 383-6963

On Mar 30, 2017, at 3:55 PM, Yue Ko <notifications@github.com<mailto:notifications@github.com>> wrote:


No, you don't need to be admin to use the python client. You should be able to use the same credential to perform the same task that you can do via the GUI.

I tried using all sorts of special characters in the password, and I could not reproduce the exception that you last reported.

If possible, maybe you can changed the password to eliminate a special character one at a time?

**Comment by ku0100** [comment] 2017-12-04 16:49
Hey @johnbelamaric, how would I go about doing this (allow insecure/include cert in request)? I don't see cert as an attribute in the Connector object. I am still having this issue and I have verified my login works when I go directly the NIOS. Thank you!

**Comment by Msojdehei** [comment] 2018-08-15 16:13
was the cert questions answered?  I'm having the same issue, how to add cert_valid 'no'? or add a cert?

**Comment by sarya-infoblox** [comment] 2022-02-17 11:02
Hi @ku0100 was your question answered or you are still facing this issue?

**Comment by sarya-infoblox** [comment] 2022-03-09 07:46
Hi @ku0100 Can you please confirm if we can close this issue or you need help?

**Comment by sarya-infoblox** [comment] 2022-03-16 08:11
Closing the issue as no response from the user.

**Closed by sarya-infoblox** 2022-03-16 08:11 UTC

**Comment by ku0100** [comment] 2022-03-16 13:34
This issue is from like 5 years ago...
